import { Timestamp } from "firebase/firestore";
export type Threp = {
  base_info: {
    character: string[];
    rank: string;
    shottype: string;
    stage: string;
  };
  player: string;
  slow_rate: number;
  stage_score: Array<number>;
  frame_count: number;
  game: number;
  date: string;
  date_on_file: string;
  z_keys: number;
  x_keys: number;
  c_keys: number;
  checksum: string;
  shift: number;
  rpy_name: string;
};
export const initialThrep: Threp = {
  base_info: {
    character: ["-"],
    rank: "-",
    shottype: "-",
    stage: "-",
  },
  player: "-",
  slow_rate: 0,
  game: 0,
  stage_score: [0],
  frame_count: 0,
  date: "-",
  date_on_file: "-",
  z_keys: 0,
  x_keys: 0,
  c_keys: 0,
  shift: 0,
  checksum: "-",
  rpy_name: "-",
};
export type PrivateUser = {
  displayName: string;
  uid: string;
  scoreRank?: number;
  achievementsRank?: number;
  CC?: number;
  admin: boolean;
  supporter: boolean;
  joindate: Timestamp;
  image?: string;
  discord?: string;
  youtube?: string;
  twitter?: string;
  favoriteGame?: string;
  bio?: string;
  totalPoints: number;
  totalScore: number;
  eventPoints: number;
  [key: string]: any; // Add an index signature
};
export type PrivateUserImageLink = {
  publicUser: PrivateUser;
  imageLink: string;
};
export type RequestReplay = {
  replay: Threp;
  user: PrivateUser;
  additionalInfo: {
    CC?: boolean;
    comment: string;
    nnn: string[];
  };
};

export type RpyReq = {
  character: string;
  rank: string;
  shottype: string;
  stage: string;
  player: string;
  slow_rate: number;
  game: number;
  stage_score: number;
  frame_count: number;
  date: string;
  date_on_file: string;
  z_keys: number;
  x_keys: number;
  c_keys: number;
  shift: number;
  checksum: string;
  rpy_name: string;
  nnn: string[];
  uid: string;
  cc: boolean;
  comment: string;
  userNickname: string;
  filePath: string;
  acceptedBy?: string;
  addDate?: Timestamp;
  points: number;
};

export const InitialUserPointRanking: UserPointRanking = {
  total: 0,
  uid: "",
  eosdEasy: 0,
  eosdNormal: 0,
  eosdHard: 0,
  eosdLunatic: 0,
  eosdExtra: 0,
  eosdEasyChecksum: "a",
  eosdNormalChecksum: "a",
  eosdHardChecksum: "a",
  eosdHardLunatic: "a",
  eosdExtraChecksum: "a",
  pcbEasy: 0,
  pcbNormal: 0,
  pcbHard: 0,
  pcbLunatic: 0,
  pcbExtra: 0,
  pcbPhantasm: 0,
  pcbEasyChecksum: "a",
  pcbNormalChecksum: "a",
  pcbHardChecksum: "a",
  pcbLunaticChecksum: "a",
  pcbExtraChecksum: "a",
  pcbPhantasmChecksum: "a",
  inEasy: 0,
  inNormal: 0,
  inHard: 0,
  inLunatic: 0,
  inExtra: 0,
  inEasyChecksum: "a",
  inNormalChecksum: "a",
  inHardChecksum: "a",
  inLunaticChecksum: "a",
  inExtraChecksum: "a",
  pofvEasy: 0,
  pofvNormal: 0,
  pofvHard: 0,
  pofvLunatic: 0,
  pofvExtra: 0,
  pofvEasyChecksum: "a",
  pofvNormalChecksum: "a",
  pofvHardChecksum: "a",
  pofvLunaticChecksum: "a",
  pofvExtraChecksum: "a",
  mofEasy: 0,
  mofNormal: 0,
  mofHard: 0,
  mofLunatic: 0,
  mofExtra: 0,
  mofEasyChecksum: "a",
  mofNormalChecksum: "a",
  mofHardChecksum: "a",
  mofLunaticChecksum: "a",
  mofExtraChecksum: "a",
  saEasy: 0,
  saNormal: 0,
  saHard: 0,
  saLunatic: 0,
  saExtra: 0,
  saEasyChecksum: "a",
  saNormalChecksum: "a",
  saHardChecksum: "a",
  saLunaticChecksum: "a",
  saExtraChecksum: "a",
  ufoEasy: 0,
  ufoNormal: 0,
  ufoHard: 0,
  ufoLunatic: 0,
  ufoExtra: 0,
  ufoEasyChecksum: "a",
  ufoNormalChecksum: "a",
  ufoHardChecksum: "a",
  ufoLunaticChecksum: "a",
  ufoExtraChecksum: "a",
  gfwEasy: 0,
  gfwNormal: 0,
  gfwHard: 0,
  gfwLunatic: 0,
  gfwExtra: 0,
  gfwEasyChecksum: "a",
  gfwNormalChecksum: "a",
  gfwHardChecksum: "a",
  gfwLunaticChecksum: "a",
  gfwExtraChecksum: "a",
  tdEasy: 0,
  tdNormal: 0,
  tdHard: 0,
  tdLunatic: 0,
  tdExtra: 0,
  tdEasyChecksum: "a",
  tdNormalChecksum: "a",
  tdHardChecksum: "a",
  tdLunaticChecksum: "a",
  tdExtraChecksum: "a",
  ddcEasy: 0,
  ddcNormal: 0,
  ddcHard: 0,
  ddcLunatic: 0,
  ddcExtra: 0,
  ddcEasyChecksum: "a",
  ddcNormalChecksum: "a",
  ddcHardChecksum: "a",
  ddcLunaticChecksum: "a",
  ddcExtraChecksum: "a",
  lolkEasy: 0,
  lolkNormal: 0,
  lolkHard: 0,
  lolkLunatic: 0,
  lolkExtra: 0,
  lolkEasyChecksum: "a",
  lolkNormalChecksum: "a",
  lolkHardChecksum: "a",
  lolkLunaticChecksum: "a",
  lolkExtraChecksum: "a",
  hsifsEasy: 0,
  hsifsNormal: 0,
  hsifsHard: 0,
  hsifsLunatic: 0,
  hsifsExtra: 0,
  hsifsEasyChecksum: "a",
  hsifsNormalChecksum: "a",
  hsifsHardChecksum: "a",
  hsifsLunaticChecksum: "a",
  hsifsExtraChecksum: "a",
  wbawcEasy: 0,
  wbawcNormal: 0,
  wbawcHard: 0,
  wbawcLunatic: 0,
  wbawcExtra: 0,
  wbawcEasyChecksum: "a",
  wbawcNormalChecksum: "a",
  wbawcHardChecksum: "a",
  wbawcLunaticChecksum: "a",
  wbawcExtraChecksum: "a",
  umEasy: 0,
  umNormal: 0,
  umHard: 0,
  umLunatic: 0,
  umExtra: 0,
  umEasyChecksum: "a",
  umNormalChecksum: "a",
  umHardChecksum: "a",
  umLunaticChecksum: "a",
  umExtraChecksum: "a",
  totalPoints: 0,
  eosdLunaticChecksum: "a",
};

export type UserPointRanking = {
  totalPoints: number;
  uid: string;
  eosdEasy: number;
  eosdNormal: number;
  eosdHard: number;
  eosdExtra: number;
  eosdLunatic: number;
  eosdEasyChecksum: string;
  eosdNormalChecksum: string;
  eosdHardChecksum: string;
  eosdExtraChecksum: string;
  eosdLunaticChecksum: string;
  pcbEasy: number;
  pcbNormal: number;
  pcbHard: number;
  pcbLunatic: number;
  pcbExtra: number;
  pcbPhantasm: number;
  pcbEasyChecksum: string;
  pcbNormalChecksum: string;
  pcbHardChecksum: string;
  pcbLunaticChecksum: string;
  pcbExtraChecksum: string;
  pcbPhantasmChecksum: string;
  inEasy: number;
  inNormal: number;
  inHard: number;
  inLunatic: number;
  inExtra: number;
  inEasyChecksum: string;
  inNormalChecksum: string;
  inHardChecksum: string;
  inLunaticChecksum: string;
  inExtraChecksum: string;
  pofvEasy: number;
  pofvNormal: number;
  pofvHard: number;
  pofvLunatic: number;
  pofvExtra: number;
  pofvEasyChecksum: string;
  pofvNormalChecksum: string;
  pofvHardChecksum: string;
  pofvLunaticChecksum: string;
  pofvExtraChecksum: string;
  mofEasy: number;
  mofNormal: number;
  mofHard: number;
  mofLunatic: number;
  mofExtra: number;
  mofEasyChecksum: string;
  mofNormalChecksum: string;
  mofHardChecksum: string;
  mofLunaticChecksum: string;
  mofExtraChecksum: string;
  saEasy: number;
  saNormal: number;
  saHard: number;
  saLunatic: number;
  saExtra: number;
  saEasyChecksum: string;
  saNormalChecksum: string;
  saHardChecksum: string;
  saLunaticChecksum: string;
  saExtraChecksum: string;
  ufoEasy: number;
  ufoNormal: number;
  ufoHard: number;
  ufoLunatic: number;
  ufoExtra: number;
  ufoEasyChecksum: string;
  ufoNormalChecksum: string;
  ufoHardChecksum: string;
  ufoLunaticChecksum: string;
  ufoExtraChecksum: string;
  gfwEasy: number;
  gfwNormal: number;
  gfwHard: number;
  gfwLunatic: number;
  gfwExtra: number;
  gfwEasyChecksum: string;
  gfwNormalChecksum: string;
  gfwHardChecksum: string;
  gfwLunaticChecksum: string;
  gfwExtraChecksum: string;
  tdEasy: number;
  tdNormal: number;
  tdHard: number;
  tdLunatic: number;
  tdExtra: number;
  tdEasyChecksum: string;
  tdNormalChecksum: string;
  tdHardChecksum: string;
  tdLunaticChecksum: string;
  tdExtraChecksum: string;
  ddcEasy: number;
  ddcNormal: number;
  ddcHard: number;
  ddcLunatic: number;
  ddcExtra: number;
  ddcEasyChecksum: string;
  ddcNormalChecksum: string;
  ddcHardChecksum: string;
  ddcLunaticChecksum: string;
  ddcExtraChecksum: string;
  lolkEasy: number;
  lolkNormal: number;
  lolkHard: number;
  lolkLunatic: number;
  lolkExtra: number;
  lolkEasyChecksum: string;
  lolkNormalChecksum: string;
  lolkHardChecksum: string;
  lolkLunaticChecksum: string;
  lolkExtraChecksum: string;
  hsifsEasy: number;
  hsifsNormal: number;
  hsifsHard: number;
  hsifsLunatic: number;
  hsifsExtra: number;
  hsifsEasyChecksum: string;
  hsifsNormalChecksum: string;
  hsifsHardChecksum: string;
  hsifsLunaticChecksum: string;
  hsifsExtraChecksum: string;
  wbawcEasy: number;
  wbawcNormal: number;
  wbawcHard: number;
  wbawcLunatic: number;
  wbawcExtra: number;
  wbawcEasyChecksum: string;
  wbawcNormalChecksum: string;
  wbawcHardChecksum: string;
  wbawcLunaticChecksum: string;
  wbawcExtraChecksum: string;
  umEasy: number;
  umNormal: number;
  umHard: number;
  umLunatic: number;
  umExtra: number;
  umEasyChecksum: string;
  umNormalChecksum: string;
  umHardChecksum: string;
  umLunaticChecksum: string;
  umExtraChecksum: string;
  [key: string]: number | string;
};
